#define GUN_BULK_PISTOL       1
#define GUN_BULK_REVOLVER     2
#define GUN_BULK_SMG          3
#define GUN_BULK_CARABINE     4
//#define GUN_BULK_RIFLE        5
#define GUN_BULK_SNIPER_RIFLE 6
#define GUN_BULK_MACHINEGUN   7

#define TARGET_NODANGER 0
#define TARGET_SEMISAFE 80
#define TARGET_SIGNIFICANT 100
#define TARGET_DANGEROUS 150
#define TARGET_MAXIMUM_DANGER 200
