name: Make changelogs

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    if: github.repository == 'infinitystation/Baystation12'
    steps:
      - name: Загрузка локальной среды
        uses: actions/checkout@v1
        with:
          fetch-depth: 25
      - name: Настройка Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Установка необходимого ПО
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Генерирование ЧЛ
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_EMAIL: "action@github.com"
          GIT_NAME: "Embodiment of Changelogs" 
        run: python tools/GenerateChangelog/generate_cl.py
